import { client } from "fetch-lube"

let myClient = client("http://localhost")
myClient = client("http://localhost", abort => abort())
myClient.get().query().then((value: Response) => value.json())
myClient.get({ mode: "no-cors" }).query({ a: "a" })
myClient.post().json({ a: "a" })
myClient.post().multiPart({ a: "a" })
myClient.post().urlEncoded({ a: "a" })
myClient.post({ mode: "no-cors" }).json().then((value: Response) => value.json())
myClient.patch().json({ a: "a" })
myClient.put().json({ a: "a" })
myClient.delete().json({ a: "a" })
myClient.head().json({ a: "a" })
myClient.options().json({ a: "a" })